In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [6]:
data=pd.read_csv("purchase_data(1).csv")
data

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17        10.0             A   
1       1000001  P00248942      F   0-17        10.0             A   
2       1000001  P00087842      F   0-17        10.0             A   
3       1000001  P00085442      F   0-17        10.0             A   
4       1000002  P00285442      M    55+        16.0             C   
...         ...        ...    ...    ...         ...           ...   
263010  1004473  P00041942      M  36-45         1.0             B   
263011  1004473  P00115142      M  36-45         1.0             B   
263012  1004473  P00188442      M  36-45         1.0             B   
263013  1004473  P00119442      M  36-45         1.0             B   
263014       10        NaN    NaN    NaN         NaN           NaN   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2             0.0                 3.0   
1                               2             0.0                 1.0   
2                               2             0.0                12.0   
3                               2             0.0                12.0   
4                              4+             0.0                 8.0   
...                           ...             ...                 ...   
263010                          3             0.0                 5.0   
263011                          3             0.0                 1.0   
263012                          3             0.0                 5.0   
263013                          3             0.0                 5.0   
263014                        NaN             NaN                 NaN   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN    8370.0  
1                      6.0                14.0   15200.0  
2                      NaN                 NaN    1422.0  
3                     14.0                 NaN    1057.0  
4                      NaN                 NaN    7969.0  
...                    ...                 ...       ...  
263010                18.0                 NaN    3722.0  
263011                 8.0                17.0   19253.0  
263012                 7.0                 NaN    3608.0  
263013                 NaN                 NaN    3604.0  
263014                 NaN                 NaN       NaN  

[263015 rows x 12 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263015 entries, 0 to 263014
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     263015 non-null  int64  
 1   Product_ID                  263014 non-null  object 
 2   Gender                      263014 non-null  object 
 3   Age                         263014 non-null  object 
 4   Occupation                  263014 non-null  float64
 5   City_Category               263014 non-null  object 
 6   Stay_In_Current_City_Years  263014 non-null  object 
 7   Marital_Status              263014 non-null  float64
 8   Product_Category_1          263014 non-null  float64
 9   Product_Category_2          181501 non-null  float64
 10  Product_Category_3          80582 non-null   float64
 11  Purchase                    263014 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 24.1+ MB


In [8]:
data=data.dropna() # to drop the null values when the % is small

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80582 entries, 1 to 263011
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   User_ID                     80582 non-null  int64  
 1   Product_ID                  80582 non-null  object 
 2   Gender                      80582 non-null  object 
 3   Age                         80582 non-null  object 
 4   Occupation                  80582 non-null  float64
 5   City_Category               80582 non-null  object 
 6   Stay_In_Current_City_Years  80582 non-null  object 
 7   Marital_Status              80582 non-null  float64
 8   Product_Category_1          80582 non-null  float64
 9   Product_Category_2          80582 non-null  float64
 10  Product_Category_3          80582 non-null  float64
 11  Purchase                    80582 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 8.0+ MB


In [ ]:
x=data['Purchase'].mean()
x # if we want to fill the null values then taking the mean of that column and filling it in that column

11628.183279144227

In [9]:
data.isnull().sum().sum()

0

In [10]:
new_duplicates=data.duplicated().sum() # to remove the duplicates from entire data
new_duplicates

0

In [11]:
data["Gender"].nunique()

2

In [12]:
data['Gender'].unique()

array(['F', 'M'], dtype=object)

In [13]:
data["Gender"].value_counts()

Gender
M    62549
F    18033
Name: count, dtype: int64

In [14]:
data["Age"].unique()

array(['0-17', '46-50', '26-35', '51-55', '36-45', '18-25', '55+'],
      dtype=object)

In [ ]:
# label encoding on categorical columns

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()

In [17]:
data.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [18]:
data["Gender"]=le.fit_transform(data["Gender"])
data["Age"]=le.fit_transform(data["Age"])
data["City_Category"]=le.fit_transform(data["City_Category"])
data["Stay_In_Current_City_Years"]=le.fit_transform(data["Stay_In_Current_City_Years"])
data["Product_ID"]=le.fit_transform(data["Product_ID"])

In [19]:
data["Gender"].unique()

array([0, 1])

In [20]:
data["Age"].unique()

array([0, 4, 2, 5, 3, 1, 6])

In [21]:
data["City_Category"].unique()

array([0, 1, 2])

In [22]:
data["Stay_In_Current_City_Years"].unique()

array([2, 1, 4, 0, 3])

In [23]:
data["Product_ID"].unique()

array([391, 284, 211, 363, 517,  58, 393, 438, 114, 123, 276, 234, 349,
       147, 508, 221, 154, 146, 275,  64, 385,  33, 107, 300, 229, 152,
        51, 351, 168, 457, 298, 239, 151, 183, 176,  90, 395, 487, 402,
       358, 419, 271,   2, 426, 411, 481,  47,  46, 332,  71, 427, 420,
       404,  40, 342, 137, 179, 479, 160,  59, 307, 125,  41, 416, 122,
       204,  45, 149, 412, 454,  77,  16, 158,  44, 113, 456, 486,   0,
        48, 191,  36, 337, 243,  29,  30, 359, 215, 190, 382, 384, 299,
       143, 213, 222, 371, 260, 145, 170, 228, 515, 273, 428, 153, 254,
       309, 320, 256,   8, 198, 314,  98,  23, 138,  84,  52,  82, 264,
       365, 368, 184, 246, 516, 108, 357,  22, 413, 335, 165, 203, 130,
        55,  89,  92, 231, 106,  76, 520, 330, 126, 128,  56, 415, 489,
       115, 208, 181, 210, 326, 397, 304,  94, 163,  26, 484, 296, 375,
       410,  85, 386, 485,  39, 116, 387, 448, 439, 483, 434, 521,   4,
       297, 322,   9, 267, 117, 459, 174, 241, 159, 378,  96, 29

In [24]:
data["User_ID"].unique()

array([1000001, 1000004, 1000005, ..., 1004295, 1004332, 1004429])

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80582 entries, 1 to 263011
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   User_ID                     80582 non-null  int64  
 1   Product_ID                  80582 non-null  int64  
 2   Gender                      80582 non-null  int64  
 3   Age                         80582 non-null  int64  
 4   Occupation                  80582 non-null  float64
 5   City_Category               80582 non-null  int64  
 6   Stay_In_Current_City_Years  80582 non-null  int64  
 7   Marital_Status              80582 non-null  float64
 8   Product_Category_1          80582 non-null  float64
 9   Product_Category_2          80582 non-null  float64
 10  Product_Category_3          80582 non-null  float64
 11  Purchase                    80582 non-null  float64
dtypes: float64(6), int64(6)
memory usage: 8.0 MB


In [26]:
data.isnull()

User_ID  Product_ID  Gender    Age  Occupation  City_Category  \
1         False       False   False  False       False          False   
6         False       False   False  False       False          False   
13        False       False   False  False       False          False   
14        False       False   False  False       False          False   
16        False       False   False  False       False          False   
...         ...         ...     ...    ...         ...            ...   
262997    False       False   False  False       False          False   
263001    False       False   False  False       False          False   
263003    False       False   False  False       False          False   
263006    False       False   False  False       False          False   
263011    False       False   False  False       False          False   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
1                            False           False               False   
6                            False           False               False   
13                           False           False               False   
14                           False           False               False   
16                           False           False               False   
...                            ...             ...                 ...   
262997                       False           False               False   
263001                       False           False               False   
263003                       False           False               False   
263006                       False           False               False   
263011                       False           False               False   

        Product_Category_2  Product_Category_3  Purchase  
1                    False               False     False  
6                    False               False     False  
13                   False               False     False  
14                   False               False     False  
16                   False               False     False  
...                    ...                 ...       ...  
262997               False               False     False  
263001               False               False     False  
263003               False               False     False  
263006               False               False     False  
263011               False               False     False  

[80582 rows x 12 columns]

In [27]:
data["Age"].head(20)

1     0
6     4
13    2
14    5
16    5
18    3
19    2
24    2
28    2
29    3
36    3
38    3
39    3
41    3
43    3
44    3
46    3
48    2
54    4
64    2
Name: Age, dtype: int64

In [28]:
data

User_ID  Product_ID  Gender  Age  Occupation  City_Category  \
1       1000001         391       0    0        10.0              0   
6       1000004         284       1    4         7.0              1   
13      1000005         211       1    2        20.0              0   
14      1000006         363       0    5         9.0              0   
16      1000006         517       0    5         9.0              0   
...         ...         ...     ...  ...         ...            ...   
262997  1004472         402       0    4        16.0              1   
263001  1004472         337       0    4        16.0              1   
263003  1004472         480       0    4        16.0              1   
263006  1004472          49       0    4        16.0              1   
263011  1004473         159       1    3         1.0              1   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
1                                2             0.0                 1.0   
6                                2             1.0                 1.0   
13                               1             1.0                 1.0   
14                               1             0.0                 5.0   
16                               1             0.0                 2.0   
...                            ...             ...                 ...   
262997                           0             1.0                 1.0   
263001                           0             1.0                 1.0   
263003                           0             1.0                 1.0   
263006                           0             1.0                 8.0   
263011                           3             0.0                 1.0   

        Product_Category_2  Product_Category_3  Purchase  
1                      6.0                14.0   15200.0  
6                      8.0                17.0   19215.0  
13                     2.0                 5.0   15665.0  
14                     8.0                14.0    5378.0  
16                     3.0                 4.0   13055.0  
...                    ...                 ...       ...  
262997                11.0                16.0   15175.0  
263001                11.0                15.0   15430.0  
263003                 2.0                15.0   15387.0  
263006                13.0                16.0    5861.0  
263011                 8.0                17.0   19253.0  

[80582 rows x 12 columns]

In [3]:
# statistics

In [2]:
#let's Suppose, it was observed that the average purchase made by the Men of the age 18-25 was 10000. Is it still the same?

# null Hypothesis - the average of is 10000
# alternate hypothesis - the mean is not 10000

In [34]:
data.sample(6,random_state=33)

User_ID  Product_ID  Gender  Age  Occupation  City_Category  \
162265  1001112          42       1    1         6.0              0   
174021  1002929         373       1    1         2.0              0   
162426  1001125          31       0    1         4.0              1   
89644   1001793         416       1    2         4.0              1   
202866  1001301           6       0    2         2.0              2   
217222  1003536         241       1    1         4.0              2   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
162265                           4             0.0                 6.0   
174021                           4             0.0                 5.0   
162426                           2             0.0                 1.0   
89644                            1             0.0                 1.0   
202866                           1             1.0                 1.0   
217222                           0             0.0                10.0   

        Product_Category_2  Product_Category_3  Purchase  
162265                 8.0                14.0   20597.0  
174021                 8.0                14.0    3522.0  
162426                 2.0                15.0   11892.0  
89644                  6.0                15.0   11822.0  
202866                 5.0                 8.0    8201.0  
217222                15.0                16.0   14275.0

In [35]:
data.head()

User_ID  Product_ID  Gender  Age  Occupation  City_Category  \
1   1000001         391       0    0        10.0              0   
6   1000004         284       1    4         7.0              1   
13  1000005         211       1    2        20.0              0   
14  1000006         363       0    5         9.0              0   
16  1000006         517       0    5         9.0              0   

    Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
1                            2             0.0                 1.0   
6                            2             1.0                 1.0   
13                           1             1.0                 1.0   
14                           1             0.0                 5.0   
16                           1             0.0                 2.0   

    Product_Category_2  Product_Category_3  Purchase  
1                  6.0                14.0   15200.0  
6                  8.0                17.0   19215.0  
13                 2.0                 5.0   15665.0  
14                 8.0                14.0    5378.0  
16                 3.0                 4.0   13055.0

In [37]:
new_data=data.loc[(data["Age"]==1) & data["Gender"]==1]

In [38]:
new_data

User_ID  Product_ID  Gender  Age  Occupation  City_Category  \
98      1000022         487       1    1        15.0              0   
103     1000022         402       1    1        15.0              0   
111     1000022         358       1    1        15.0              0   
127     1000025         332       1    1         4.0              2   
128     1000025          71       1    1         4.0              2   
...         ...         ...     ...  ...         ...            ...   
262758  1004446         180       1    1        18.0              1   
262759  1004446         394       1    1        18.0              1   
262760  1004446          23       1    1        18.0              1   
262764  1004446          75       1    1        18.0              1   
262952  1004465         209       1    1         4.0              0   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
98                               4             0.0                 1.0   
103                              4             0.0                 1.0   
111                              4             0.0                 2.0   
127                              4             0.0                 1.0   
128                              4             0.0                 1.0   
...                            ...             ...                 ...   
262758                           1             1.0                 1.0   
262759                           1             1.0                 1.0   
262760                           1             1.0                 1.0   
262764                           1             1.0                 5.0   
262952                           1             1.0                 2.0   

        Product_Category_2  Product_Category_3  Purchase  
98                     8.0                17.0   12099.0  
103                   11.0                16.0   12098.0  
111                    4.0                15.0    9564.0  
127                    5.0                 9.0   15361.0  
128                    2.0                15.0   15770.0  
...                    ...                 ...       ...  
262758                 2.0                15.0   11512.0  
262759                15.0                18.0   11521.0  
262760                 2.0                13.0    3988.0  
262764                 8.0                17.0    5444.0  
262952                 3.0                 4.0    3240.0  

[11904 rows x 12 columns]

In [72]:
samplesize = 1000
sample=new_data.sample(samplesize,random_state=88)
sample

User_ID  Product_ID  Gender  Age  Occupation  City_Category  \
48261   1001399         504       1    1        17.0              2   
57327   1002859         182       1    1         1.0              2   
207997  1002023         299       1    1         4.0              1   
237584  1000676         454       1    1        16.0              1   
222962  1004350         384       1    1         2.0              2   
...         ...         ...     ...  ...         ...            ...   
82264   1000714         254       1    1         4.0              1   
69508   1004635         284       1    1         4.0              1   
199210  1000770          93       1    1         4.0              1   
220332  1003965          88       1    1        11.0              2   
204963  1001628         136       1    1        20.0              1   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
48261                            1             0.0                 1.0   
57327                            0             0.0                 1.0   
207997                           2             1.0                 3.0   
237584                           1             1.0                 5.0   
222962                           4             0.0                 1.0   
...                            ...             ...                 ...   
82264                            2             0.0                 1.0   
69508                            2             0.0                 1.0   
199210                           2             1.0                 1.0   
220332                           3             0.0                 2.0   
204963                           1             0.0                 8.0   

        Product_Category_2  Product_Category_3  Purchase  
48261                  2.0                 9.0   11915.0  
57327                  2.0                15.0   15433.0  
207997                 4.0                 5.0   13317.0  
237584                 8.0                17.0    6940.0  
222962                 2.0                15.0    7664.0  
...                    ...                 ...       ...  
82264                 15.0                16.0   15472.0  
69508                  8.0                17.0   19533.0  
199210                 2.0                 3.0   11738.0  
220332                 8.0                18.0   16082.0  
204963                14.0                17.0    5996.0  

[1000 rows x 12 columns]

T-test

In [45]:
from scipy.stats import ttest_1samp

In [46]:
t_stat,P_value=ttest_1samp(sample["Purchase"],10000)

In [47]:
P_value

4.671124853473394e-31

In [48]:
if P_value<0.05:
  print("Reject Null Hypothesis")
else:
  print("Accept Null Hypothesis")

Reject Null Hypothesis


In [49]:
data_men=data.loc[(data["Gender"]==1)&(data["Age"]==1)]
data_women=data.loc[(data["Gender"]==0)&(data["Age"]==1)]

In [51]:
data_men.shape

(11904, 12)

In [53]:
data_women.shape

(3417, 12)

In [58]:
data_men_Sample=data_men.sample(500,random_state=233)
data_women_Sample=data_women.sample(500,random_state=789)

In [55]:
data_men_Sample.shape

(500, 12)

In [56]:
data_women_Sample.shape

(500, 12)

In [59]:
print(data_men_Sample.Purchase.var())
print(data_women_Sample.Purchase.var())

27741598.981146302
25918106.698496982


T-test for two sample when the variance is unequal

In [60]:
from scipy.stats import ttest_ind

In [61]:
t_stat2,p_value2=ttest_ind(data_men_Sample["Purchase"],data_women_Sample["Purchase"],equal_var=True)
print(p_value2)

0.0008339484729592622


In [62]:
if p_value2<0.05:
  print("Reject Null Hypothesis")
else:
  print("Accept Null Hypothesis")

Reject Null Hypothesis


Z-test

In [73]:
data_new=data.loc[data["Purchase"]>10000]

In [75]:
data_new.shape

(49390, 12)

In [77]:
# to find the no of women in the data
women_count = data_new["Gender"].value_counts()[0]
women_count

10175

In [82]:
# to find the number of observations
nobs = len(data_new["Gender"])
p0 = 0.35 #(given)

In [83]:
nobs

49390

In [84]:
# now to find the Z-test proportion

from statsmodels.stats.proportion import proportions_ztest

In [85]:
z_stat,p_value=proportions_ztest(count=women_count,nobs=nobs,value=p0)
print(p_value)

0.0


In [86]:
if p_value2<0.05:
  print("Reject Null Hypothesis")
else:
  print("Accept Null Hypothesis")

Reject Null Hypothesis


Chi-Square test

In [87]:
# this is used to find whether the variables are dependent to each other or not

In [88]:
import pandas as pd
from scipy.stats import chi2_contingency

In [89]:
contingency_table=pd.crosstab(data["Purchase"],data["Product_Category_1"])

In [90]:
contingency_table.tail(10)

Product_Category_1  1.0   2.0   3.0   4.0   5.0   6.0   8.0   10.0  11.0  \
Purchase                                                                   
23929.0                0     0     0     0     0     0     0     1     0   
23932.0                0     0     0     0     0     0     0     1     0   
23934.0                0     0     0     0     0     0     0     1     0   
23935.0                0     0     0     0     0     0     0     1     0   
23936.0                0     0     0     0     0     0     0     1     0   
23939.0                0     0     0     0     0     0     0     2     0   
23944.0                0     0     0     0     0     0     0     1     0   
23946.0                0     0     0     0     0     0     0     1     0   
23953.0                0     0     0     0     0     0     0     2     0   
23958.0                0     0     0     0     0     0     0     1     0   

Product_Category_1  12.0  13.0  15.0  
Purchase                              
23929.0                0     0     0  
23932.0                0     0     0  
23934.0                0     0     0  
23935.0                0     0     0  
23936.0                0     0     0  
23939.0                0     0     0  
23944.0                0     0     0  
23946.0                0     0     0  
23953.0                0     0     0  
23958.0                0     0     0

In [91]:
contingency_table

Product_Category_1  1.0   2.0   3.0   4.0   5.0   6.0   8.0   10.0  11.0  \
Purchase                                                                   
186.0                  0     0     0     0     0     0     0     0     0   
187.0                  0     0     0     0     0     0     0     0     0   
188.0                  0     0     0     0     0     0     0     0     0   
199.0                  0     0     0     0     0     0     0     0     0   
200.0                  0     0     0     0     0     0     0     0     0   
...                  ...   ...   ...   ...   ...   ...   ...   ...   ...   
23939.0                0     0     0     0     0     0     0     2     0   
23944.0                0     0     0     0     0     0     0     1     0   
23946.0                0     0     0     0     0     0     0     1     0   
23953.0                0     0     0     0     0     0     0     2     0   
23958.0                0     0     0     0     0     0     0     1     0   

Product_Category_1  12.0  13.0  15.0  
Purchase                              
186.0                  0     2     0  
187.0                  0     1     0  
188.0                  0     2     0  
199.0                  0     1     0  
200.0                  0     1     0  
...                  ...   ...   ...  
23939.0                0     0     0  
23944.0                0     0     0  
23946.0                0     0     0  
23953.0                0     0     0  
23958.0                0     0     0  

[12341 rows x 12 columns]

In [92]:
chi2,p_value,dof,expected=chi2_contingency(contingency_table)
print(p_value)

0.0


ANOVA

In [93]:
from scipy.stats import f_oneway

In [94]:
samp1=data["Product_Category_1"]
samp2=data["Product_Category_2"]
samp3=data["Product_Category_3"]

In [95]:
a_stat,p_value=f_oneway(samp1,samp2,samp3)

In [96]:
p_value

0.0

In [97]:
print(data["Product_Category_1"].mean())
print(data["Product_Category_2"].mean())
print(data["Product_Category_3"].mean())

2.7383658881636097
6.892085081035467
12.65829837929066
